include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'

renovate:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "push"'

image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login $CI_REGISTRY_IMAGE -u Satont -p $CI_REGISTRY_PASSWORD

build:api:
  only:
    - master
  script:
    - |

      IMAGE_TAGGED=$CI_REGISTRY_IMAGE/satont/tsuwari/api:$CI_COMMIT_REF_SLUG
      IMAGE_LATEST=$CI_REGISTRY_IMAGE/satont/tsuwari/api:latest

      docker buildx build \
        --push
        --tag $IMAGE_TAGGED \
        --tag $IMAGE_LATEST \
        --file apps/api/Dockerfile \
        --platform linux/amd64,linux/arm64
        .

after_script:
  - docker logout $CI_REGISTRY_IMAGE