version: "3.7"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 54310:8080
    environment:
      - ADMINER_PLUGINS=enum-types

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tsuwari
      POSTGRES_PASSWORD: tsuwari
      POSTGRES_DB: tsuwari

  backup:
    restart: unless-stopped
    image: satont/postgresql-backup-s3
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      SCHEDULE: ${S3_SCHEDULE}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}

  migrations:
    restart: unless-stopped
    image: satont/tsuwari:migrations
    env_file:
      - .env
    depends_on:
      - postgres

  redis:
    restart: unless-stopped
    image: redis:latest
    volumes:
      - ./redis-data:/data

  nats:
    restart: unless-stopped
    image: nats:latest

  api:
    restart: unless-stopped
    image: satont/tsuwari:api
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 6
    ports:
      - 3002:3002
    depends_on:
      - migrations
      - redis

  bots:
    restart: unless-stopped
    image: satont/tsuwari:bots
    env_file:
      - .env
    depends_on:
      - migrations
      - redis

  scheduler:
    restart: unless-stopped
    image: satont/tsuwari:scheduler
    env_file:
      - .env
    depends_on:
      - migrations
      - redis

  streamstatus:
    restart: unless-stopped
    image: satont/tsuwari:streamstatus
    env_file:
      - .env
    depends_on:
      - migrations
      - redis
