name: Renovate
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  push:

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}